from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from library_api.models.base_model import Model
from library_api import util


class Book(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, title=None, author=None, date_joined=None):  # noqa: E501
        """Book - a model defined in OpenAPI

        :param id: The id of this Book.  # noqa: E501
        :type id: int
        :param title: The title of this Book.  # noqa: E501
        :type title: str
        :param author: The author of this Book.  # noqa: E501
        :type author: str
        :param date_joined: The date_joined of this Book.  # noqa: E501
        :type date_joined: datetime
        """
        self.openapi_types = {
            'id': int,
            'title': str,
            'author': str,
            'date_joined': datetime
        }

        self.attribute_map = {
            'id': 'id',
            'title': 'title',
            'author': 'author',
            'date_joined': 'date_joined'
        }

        self._id = id
        self._title = title
        self._author = author
        self._date_joined = date_joined

    @classmethod
    def from_dict(cls, dikt) -> 'Book':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Book of this Book.  # noqa: E501
        :rtype: Book
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Book.

        Book ID  # noqa: E501

        :return: The id of this Book.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Book.

        Book ID  # noqa: E501

        :param id: The id of this Book.
        :type id: int
        """

        self._id = id

    @property
    def title(self) -> str:
        """Gets the title of this Book.

        Book title  # noqa: E501

        :return: The title of this Book.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Book.

        Book title  # noqa: E501

        :param title: The title of this Book.
        :type title: str
        """

        self._title = title

    @property
    def author(self) -> str:
        """Gets the author of this Book.

        Book author  # noqa: E501

        :return: The author of this Book.
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author: str):
        """Sets the author of this Book.

        Book author  # noqa: E501

        :param author: The author of this Book.
        :type author: str
        """

        self._author = author

    @property
    def date_joined(self) -> datetime:
        """Gets the date_joined of this Book.

        Date when book was added  # noqa: E501

        :return: The date_joined of this Book.
        :rtype: datetime
        """
        return self._date_joined

    @date_joined.setter
    def date_joined(self, date_joined: datetime):
        """Sets the date_joined of this Book.

        Date when book was added  # noqa: E501

        :param date_joined: The date_joined of this Book.
        :type date_joined: datetime
        """

        self._date_joined = date_joined
