from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from library_api.models.base_model import Model
from library_api.models.book import Book
from library_api import util

from library_api.models.book import Book  # noqa: E501

class CreateBook201Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, book=None):  # noqa: E501
        """CreateBook201Response - a model defined in OpenAPI

        :param book: The book of this CreateBook201Response.  # noqa: E501
        :type book: Book
        """
        self.openapi_types = {
            'book': Book
        }

        self.attribute_map = {
            'book': 'book'
        }

        self._book = book

    @classmethod
    def from_dict(cls, dikt) -> 'CreateBook201Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The createBook_201_response of this CreateBook201Response.  # noqa: E501
        :rtype: CreateBook201Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def book(self) -> Book:
        """Gets the book of this CreateBook201Response.


        :return: The book of this CreateBook201Response.
        :rtype: Book
        """
        return self._book

    @book.setter
    def book(self, book: Book):
        """Sets the book of this CreateBook201Response.


        :param book: The book of this CreateBook201Response.
        :type book: Book
        """

        self._book = book
