from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from library_api.models.base_model import Model
from library_api.models.book import Book
from library_api import util

from library_api.models.book import Book  # noqa: E501

class DeleteBook200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, book_deleted=None):  # noqa: E501
        """DeleteBook200Response - a model defined in OpenAPI

        :param book_deleted: The book_deleted of this DeleteBook200Response.  # noqa: E501
        :type book_deleted: Book
        """
        self.openapi_types = {
            'book_deleted': Book
        }

        self.attribute_map = {
            'book_deleted': 'book_deleted'
        }

        self._book_deleted = book_deleted

    @classmethod
    def from_dict(cls, dikt) -> 'DeleteBook200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The deleteBook_200_response of this DeleteBook200Response.  # noqa: E501
        :rtype: DeleteBook200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def book_deleted(self) -> Book:
        """Gets the book_deleted of this DeleteBook200Response.


        :return: The book_deleted of this DeleteBook200Response.
        :rtype: Book
        """
        return self._book_deleted

    @book_deleted.setter
    def book_deleted(self, book_deleted: Book):
        """Sets the book_deleted of this DeleteBook200Response.


        :param book_deleted: The book_deleted of this DeleteBook200Response.
        :type book_deleted: Book
        """

        self._book_deleted = book_deleted
