from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from library_api.models.base_model import Model
from library_api.models.book import Book
from library_api import util

from library_api.models.book import Book  # noqa: E501

class GetBooks200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, books=None):  # noqa: E501
        """GetBooks200Response - a model defined in OpenAPI

        :param books: The books of this GetBooks200Response.  # noqa: E501
        :type books: List[Book]
        """
        self.openapi_types = {
            'books': List[Book]
        }

        self.attribute_map = {
            'books': 'books'
        }

        self._books = books

    @classmethod
    def from_dict(cls, dikt) -> 'GetBooks200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The getBooks_200_response of this GetBooks200Response.  # noqa: E501
        :rtype: GetBooks200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def books(self) -> List[Book]:
        """Gets the books of this GetBooks200Response.


        :return: The books of this GetBooks200Response.
        :rtype: List[Book]
        """
        return self._books

    @books.setter
    def books(self, books: List[Book]):
        """Sets the books of this GetBooks200Response.


        :param books: The books of this GetBooks200Response.
        :type books: List[Book]
        """

        self._books = books
